kind: Namespace
apiVersion: v1
metadata:
  name: aks-blazor
  labels:
    {{- include "blazorgeek.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled

